### PR TITLE
Make `$in` and `$nin` work with arrays

### PR DESCRIPTION
**Pull request by dsantosmerino**
Similar to https://github.com/growthbook/growthbook/pull/1246, trying to have the same behavior and the latest features in this SDK.

### CODE REVIEW

**Comment by tinahollygb** [comment]
Looks like you may be developing against an older version of the codebase because you have some conflicts. I can review once resolved.

**Comment by dsantosmerino** [comment]
Rebased @tinahollygb, the conflict was only in the `badge.svg` file.

**Comment by tinahollygb** [comment]
@dsantosmerino your changes were merged into a separate branch but they are failing CI. Can you fix the issues and contribute a new PR?

**Comment by dsantosmerino** [comment]
Done @tinahollygb - https://github.com/growthbook/growthbook-ruby/pull/28. Could it make sense to add those checks to PRs so any contributor could have CI feedback without you merging in a specific branch?

**Comment by tinahollygb** [comment]
Great @dsantosmerino I'll take a look. 

Regarding your question:

> Could it make sense to add those checks to PRs so any contributor could have CI feedback without you merging in a specific branch?

Yes, that's currently a problem we have in our other repos and we're trying to figure out the best approach for that too as there are security considerations with this. We also expect contributors to run lint and test tasks locally. All of this is outlined in the `CONTRIBUTING.MD` file (the standard way of outlining how to contribute to an open-source project). You can read that for more detailed instructions but you can run all tasks with `rake` in the terminal in the root of the repository.

**Pull request merged**
